{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4ce3a79c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "* * * * * * *         * * * * * *         * * * * * *     * * * * * *   *                       *                                                                                                       \n",
      "*           *         *         *         *               *         *   * *                   * *                                                                                                       \n",
      "*           *         *         *         *               *         *   *   *               *   *                                                                                                       \n",
      "*           *         *         *         *               *         *   *     *           *     *                                                                                                       \n",
      "*           *         *         *         *               *         *   *       *       *       *                                                                                                       \n",
      "* * * * * * *         * * * * * *         * * * * * *     * * * * * *   *           *           *                                                                                                       \n",
      "*                     *         *                   *     *         *   *                       *                                                                                                       \n",
      "*                     *         *                   *     *         *   *                       *                                                                                                       \n",
      "*                     *         *                   *     *         *   *                       *                                                                                                       \n",
      "*                     *         *                   *     *         *   *                       *                                                                                                       \n",
      "*                     *         *         * * * * * *     *         *   *                       *                                                                                                       \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n",
      "                                                                                                                                                                                                        \n"
     ]
    }
   ],
   "source": [
    "for row in range (100):\n",
    "    for col in range (100):\n",
    "        if col==0 and row==0:\n",
    "            print(\"*\",end=\" \")\n",
    "        elif col==1 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==2 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==3 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==4 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==5 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==6 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "                \n",
    "        elif col==0 and row==1:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==0 and row==2:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==0 and row==3:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==0 and row==4:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==0 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==0 and row==6:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==0 and row==7:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==0 and row==8:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==0 and row==9:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==0 and row==10:\n",
    "             print(\"*\",end=\" \")\n",
    "        \n",
    "        elif col==1 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==2 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==3 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==4 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==5 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==6 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "                \n",
    "        elif col==6 and row==1:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==6 and row==2:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==6 and row==3:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==6 and row==4:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==6 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "                \n",
    "        elif col==11 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==12 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==13 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==14 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==15 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==16 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        \n",
    "                \n",
    "        elif col==11 and row==1:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==11 and row==2:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==11 and row==3:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==11 and row==4:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==11 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==11 and row==6:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==11 and row==7:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==11 and row==8:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==11 and row==9:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==11 and row==10:\n",
    "             print(\"*\",end=\" \")\n",
    "        \n",
    "        elif col==16 and row==1:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==16 and row==2:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==16 and row==3:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==16 and row==4:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==16 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==16 and row==6:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==16 and row==7:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==16 and row==8:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==16 and row==9:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==16 and row==10:\n",
    "             print(\"*\",end=\" \")\n",
    "        \n",
    "        elif (col==12 or col == 13 or col == 14 or col == 15) and row==5:\n",
    "            print(\"*\",end=\" \")\n",
    "            \n",
    "        elif col==21 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==22 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==23 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==24 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==25 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==26 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "                \n",
    "        elif col==21 and row==1:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==21 and row==2:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==21 and row==3:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==21 and row==4:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==21 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        \n",
    "        elif (col==22 or col == 23 or col == 24 or col == 25 or col == 26) and row==5:\n",
    "            print(\"*\",end=\" \")\n",
    "            \n",
    "            \n",
    "        elif col==26 and row==6:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==26 and row==7:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==26 and row==8:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==26 and row==9:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==26 and row==10:\n",
    "             print(\"*\",end=\" \")\n",
    "                \n",
    "        elif (col==21 or col == 22 or col == 23 or col == 24 or col == 25) and row==10:\n",
    "            print(\"*\",end=\" \")\n",
    "            \n",
    "        elif col==29 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==30 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==31 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==32 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==33 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==34and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "                \n",
    "        elif col==29 and row==1:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==29 and row==2:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==29 and row==3:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==29 and row==4:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==29 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==29 and row==6:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==29 and row==7:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==29 and row==8:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==29 and row==9:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==29 and row==10:\n",
    "             print(\"*\",end=\" \")\n",
    "                \n",
    "                \n",
    "        elif col==34 and row==1:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==34 and row==2:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==34 and row==3:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==34 and row==4:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==34 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==34 and row==6:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==34 and row==7:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==34 and row==8:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==34 and row==9:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==34 and row==10:\n",
    "             print(\"*\",end=\" \")\n",
    "                \n",
    "    \n",
    "        elif (col==30 or col == 31 or col == 32 or col == 33 ) and row==5:\n",
    "            print(\"*\",end=\" \")\n",
    "            \n",
    "            \n",
    "        elif col==36 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==36 and row==1:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==36 and row==2:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==36 and row==3:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==36 and row==4:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==36 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==36 and row==6:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==36 and row==7:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==36 and row==8:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==36 and row==9:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==36 and row==10:\n",
    "             print(\"*\",end=\" \")\n",
    "                \n",
    "        \n",
    "        elif col==48 and row==0:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==48 and row==1:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==48 and row==2:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==48 and row==3:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==48 and row==4:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==48 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==48 and row==6:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==48 and row==7:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==48 and row==8:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==48 and row==9:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==48 and row==10:\n",
    "             print(\"*\",end=\" \")\n",
    "                \n",
    "                \n",
    "        elif col==42 and row==5:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==37 and row==1:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==38 and row==2:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==39 and row==3:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==40 and row==4:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==44 and row==4:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==45 and row==3:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==46 and row==2:\n",
    "             print(\"*\",end=\" \")\n",
    "        elif col==47 and row==1:\n",
    "             print(\"*\",end=\" \")\n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        else:\n",
    "            print(end=\"  \")\n",
    "    print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea5fa70f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
